### ISSUE TITLE
Docker version problem

### ISSUE THREAD

**Issue by jhahkala** [atos-ari-aeon/fiware-cloud-messaging-platform#1]
Hi,

I tried the docker version as described in the readme.md, but the rest part failed with:

rest      | broker-manager@0.2.1 node_modules/broker-manager
rest      | âââ moment@2.5.1
rest      | âââ amqp@0.2.0 (lodash@1.3.1)
rest      | âââ winston@0.7.2 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, colors@0.6.2, async@0.2.10, pkginfo@0.3.1, request@2.16.6)
rest      |
rest      | module.js:340
rest      |     throw err;
rest      |           ^
rest      | Error: Cannot find module 'express'
rest      |     at Function.Module._resolveFilename (module.js:338:15)
rest      |     at Function.Module._load (module.js:280:25)
rest      |     at Module.require (module.js:364:17)
rest      |     at require (module.js:380:17)
rest      |     at Object.<anonymous> (/aeon_data/app.js:29:15)
rest      |     at Module._compile (module.js:456:26)
rest      |     at Object.Module._extensions..js (module.js:474:10)
rest      |     at Module.load (module.js:356:32)
rest      |     at Function.Module._load (module.js:312:12)
rest      |     at Function.Module.runMain (module.js:497:10)
rest exited with code 0

Other parts seemed to start fine.

Any advice how to fix this?

**Comment by jhahkala** [comment]
ah, restarting it made it work...
